name = "Sisyphus"
author = "SDT"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26e03a46c5ace74082c3b5259f9e251e442cc7aa84fb3b2285fafdae7f01914f"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
