name = "Sisyphus S3"
author = "Sisyphus Dev Team"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc30f14a4420fbe32f0542a9e0b75dc437681b33b94e4f154bbba45b3557e70f"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
