#Allow rudimentary pathfinding on ships
aiOnShips = false
#Allow natural mob spawning on ships
allowMobSpawns = true
#Buoyancy factor added per cubic meter of air pocket inside a ship
buoyancyFactorPerPocketVolume = 0.005
#Default elasticity coefficient for blocks. Higher values make blocks more bouncy
defaultBlockElasticity = 0.3
#Default friction coefficient for blocks. Lower values make blocks more slippery
defaultBlockFriction = 0.5
#Default block hardness (unused value, placeholder for later)
defaultBlockHardness = 1.0
#Default mass for blocks that do not have it defined in data or code. Blocks with masses below 100 float in water
defaultBlockMass = 100.0
#The default grace timer for splitting. A split won't occur after a block break at a position until this many ticks have passed. Note that setting this too high may prevent things like explosions from properly launching split ships. (in ticks)
defaultSplitGraceTimer = 2
#By default, the vanilla server prevents block interacts past a certain distance to prevent cheat clients from breaking blocks halfway across the map. This approach breaks down in the face of extremely large ships, where the distance from the block origin to the nearest face is greater than the interact distance check allows.
enableInteractDistanceChecks = true
#By default, the server checks that player movement is legal, and if it isn't, rubber-bands the player with the infamous "moved too quickly" message. Since players on VS ships will move illegally, they will be affected by this check frequently. This option disables that check. (it doesn't work very well anyway, don't worry)
enableMovementChecks = false
#If true, enables buoyancy from serverside air pockets.
enablePocketBuoyancy = true
#Enable splitting in worldspace. (Experimental!)
enableWorldSplitting = false
#Blast force in newtons of a TNT explosion at the center of the explosion.
explosionBlastForce = 100000.0
#Minimum scale of ships
minScaling = 0.5
#Scale of the mini ship creator
miniShipSize = 0.5
#If true, prevents water and other fluids from flowing out of the ship's bounding box.
preventFluidEscapingShip = false
#If true, when a mob gets unloaded, its position on a ship is saved such that if the ship is moved, when the mob loads back in it will be teleported to the same position in the ship. This helps prevent mobs from falling off of ships.
saveMobsPositionOnShip = false
#If true, when a player disconnects, their position on the ship is saved such that if the ship is moved, when they reconnect they will be teleported to the same position in the ship as they left, instead of being left behind.
teleportReconnectedPlayers = false
#If true, teleportation into the shipyard is redirected to the ship it belongs to instead.
transformTeleports = true

[CBC]
	#Should cannon shots apply a recoil force to ships
	shellRecoil = false
	#The force multiplier applied to recoil on ships
	shellRecoilMult = 500000.0

[Commands]
	#The permission level required to use the /vs backend command. Must be 0 <= x <= 4
	changeBackendCommandPerms = 4
	#The permission level required to use the /vs delete command. Must be 0 <= x <= 4
	deleteShipCommandPerms = 2
	#The permission level required to use the /vs get-air and /vs get-gravity command. Must be 0 <= x <= 4
	getAirValuesPerms = 0
	#The permission level required to use the /vs get-ship command. Must be 0 <= x <= 4
	getShipCommandPerms = 0
	#The permission level required to use the /vs remass command. Must be 0 <= x <= 4
	remassShipCommandPerms = 2
	#The permission level required to use the /vs rename command. Must be 0 <= x <= 4
	renameShipCommandPerms = 2
	#The permission level required to use the /vs scale command. Must be 0 <= x <= 4
	scaleShipCommandPerms = 2
	#The permission level required to use the /vs set-static command. Must be 0 <= x <= 4
	setStaticShipCommandPerms = 2
	#The permission level required to use the /vs teleport command. Must be 0 <= x <= 4
	teleportShipCommandPerms = 2

[ComputerCraft]
	#Turtles leaving scaled up/down ship may cause issuesEnable/Disable Turtles Leaving Scaled Ships?
	canTurtlesLeaveScaledShips = false

[Dynmap]
	#Show Ships as Icon Markers on Dynmap
	showIconMarkers = true
	#Show Ships as Polyline Markers on Dynmap
	showPolylineMarkers = true
	#Show the Ship ID in the label
	showShipId = true
	#Show the Ship Mass in the label
	showShipMass = true

["FTB Chunks"]
	#Are Ships protected by FTB Chunk Claims?
	shipsProtectedByClaims = true
	#Are ships protected outside of build height (max and min)?
	shipsProtectionOutOfBuildHeight = false

["Weather 2"]
	#If VS ships are affected by Weather2
	enableWeatherCompat = true
	#Storm effect dampening on VS ships
	stormDampening = 0.0
	#In what range storms affect VS ships
	stormRange = 150.0
	#The maximum velocity a VS ship can travel because of wind
	windMaxVel = 20.0
	#How much Weather 2's wind affects VS ships
	windMultiplier = 0.10000000149011612

