
[Messages]
	#Action bar gun noise warning message, displayed when half of the threshold is reached.
	noiseWarningMsg = "This gun is too loud.."
	#Whether to send the noise warning message in the chat or the action bar, true will send it to the chat and false will use the action bar
	noiseWarningMessageInChat = false
	#Message for when the horde is alerted by your gun's noise, sent when the threshold is reached.
	hordeStartMsg = "The loud noise is attracting zombies.."
	#Whether to send the horde start message in the chat or the action bar, true will send it to the chat and false will use the action bar
	hordeStartMessageInChat = false

[Zombie_Attraction]
	#Choose which mobs to spawn
	mobs = ["minecraft:zombie"]
	#Time window for noise (in seconds).
	#Range: 0 ~ 9223372036854775807
	timeLimit = 300
	#Cooldown between each trigger (in seconds)
	#Range: 0 ~ 9223372036854775807
	cooldown = 300
	#The radius of the area where zombies can hear your shots
	#Range: 0.0 ~ 1.7976931348623157E308
	radius = 50.0
	#How many shots until a horde is triggered
	#Range: > 1
	threshold = 60
	#How many zombies to spawn, only works with use horde set to false
	#Range: > 1
	spawnCount = 5
	#HORDELESS MODE MAY HAVE ISSUES, PLEASE REPORT THEM
	#Whether to start a horde or use the hordeless mode, useful for multiplayer servers and difficulty handling as the hordeless mode allows you to select the amount of entities
	useHorde = false
	#Sets the spawntable for the horde started by the mod. only if you're using the hordes. set it to empty to use the default, usage is hordes:name
	hordeSpawnTable = ""
	#Duration of the horde (in ticks) (only works with use horde set to true)
	#Range: > 1
	hordeDuration = 2400

[Gun]
	#Whether to not count shots if the player is encased or not (For simplicity, this works by checking if you are under a block and have no sky light coming to you.)
	ignoreEncased = true
	#Whether to ignore shots if the gun has a silencer on or not.
	ignoreSilencer = true

