
[gameplay]
	#Set true if you want to reload all your guns when respawn
	respawn_reload = false
	#Set false if you want to show kill indication ONLY while killing an entity with a gun
	global_indication = false
	#Set true if you want to refill your armor plate when respawn
	respawn_auto_armor = false

